name: Yort.Humm.Instore.Build

on: 
  push:
    branches: master
    tags: '**'
  pull_request:

jobs:
  build:

    runs-on: windows-latest
    env:
      Humm_Test_Sandbox_DeviceKey: ${{ secrets.Test_Sandbox_DeviceKey }}    
      Humm_Test_Sandbox_MerchantId: ${{ secrets.Test_Sandbox_MerchantId }}    
      Humm_Test_Sandbox_DeviceId: ${{ secrets.Test_Sandbox_DeviceId }}    
      Humm_Test_Sandbox_DeviceRegistrationKey: ${{ secrets.Test_Sandbox_DeviceRegistrationKey }}    
      Humm_Test_Sandbox_NewDeviceId: ${{ secrets.Test_Sandbox_NewDeviceId }}    

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run Tests
      run: dotnet test --verbosity normal
