name: Yort.Humm.InStore.CD

on: 
  push:
    branches: master
    tags: '**'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    env:
      Test_Sandbox_DeviceKey: ${{ secrets.Test_Sandbox_DeviceKey }}    
      Test_Sandbox_MerchantId: ${{ secrets.Test_Sandbox_MerchantId }}    
      Test_Sandbox_DeviceId: ${{ secrets.Test_Sandbox_DeviceId }}    
    steps:
    - name: Checkout
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run Tests
      run: dotnet test --verbosity normal
